spring.application.name=salud-backend
d
spring.datasource.url=jdbc:postgresql://localhost:5432/salud_db
spring.datasource.username=salud_app
spring.datasource.password=ClaveApp#2026

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect