server.port=8085
spring.application.name=salud-backend
d
spring.datasource.url=jdbc:postgresql://localhost:5432/salud_db
spring.datasource.username=salud_app
spring.datasource.password=AbcApp#2026

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#MENSAJES DE VALIDACION
spring.messages.basename=messages
spring.messages.encoding=UTF-8

# =========================
# JWT CONFIG
# =========================
jwt.secret=YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXoxMjM0NTY3ODkwQUJDREVGRw==
jwt.expiration-ms=3600000
jwt.refresh-expiration-ms=86400000